includes = ["multitest-demo-subfolder/*.toml"]

[[tests]]
name = "true"
command = ["true"]

[[tests]]
name = "false"
command = ["false"]

[[tests]]
name = "command_that_don't_exist"
command = ["command_that_don't_exist"]

[[tests]]
name = "pwd"
command = ["pwd"]

[[tests]]
name = "variables1-{{foo}}-{{bar}}{% if capitalize %}-capitalize{% endif %}"
command = ["echo", "{{foo}}", "{% if capitalize %}{{bar | capitalize}}{% else %}{{bar}}{% endif %}"]

[tests.variables]
foo = ["aa", "bb"]
bar = ["c c", "dd"]
capitalize = [true, false]


[[tests]]
name = "variables2-{{foo}}-{{bar}}"
command = ["env"]
clear_env = true

[[tests.env]]
name = "FOO"
value = "{{foo}}"

[[tests.env]]
name = "BAR-{{foo | upcase}}"
value = "{{bar}}"

[[tests.env]]
name = "TEST_NAME"
value = "{{name}}"

[tests.variables]
foo = ["aa", "bb"]
bar = ["c c", "dd"]
